apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nodes
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nodes
subjects:
- kind: ServiceAccount
  name: nodes
  namespace: system
