apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mondoo-operator.fullname" . }}-controller-manager
  labels:
  {{- include "mondoo-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mondoo-operator.fullname" . }}-k8s-resources-scanning
  labels:
  {{- include "mondoo-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.k8SResourcesScanning.serviceAccount.annotations | nindent 4 }}
