apiVersion: k8s.mondoo.com/v1alpha1
kind: MondooAuditConfig
metadata:
  name: mondoo-client
  namespace: mondoo-operator
spec:
  workloads:
    enable: true
  nodes:
    enable:  true
  webhooks:
    enable: false
  mondooSecretRef: mondoo-client
  
