name: E2E Tests for OLM

on:
  workflow_call:
    inputs:
      bundle-img:
        description: "bundle image that is used for e2e testing"
        required: true
        type: string

  workflow_dispatch:
    inputs:
      bundle-img:
        description: "bundle image that is used for e2e testing"
        required: true
        type: string

jobs:
  e2e-olm:
    name: E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: "${{ env.golang-version }}"
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
      - name: Install operator-sdk
        id: operator-sdk
        run: |
          export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
          export OS=$(uname | awk '{print tolower($0)}')
          export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.18.1
          curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
          gpg --keyserver keyserver.ubuntu.com --recv-keys 052996E2A20B5C7E
          curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt
          curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt.asc
          gpg -u "Operator SDK (release) <cncf-operator-sdk@cncf.io>" --verify checksums.txt.asc
          grep operator-sdk_${OS}_${ARCH} checksums.txt | sha256sum -c -
          chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk
      - name: Install olm
        run: |
          trap 'echo "Saving OLM logs" ; kubectl get pods --namespace mondoo-operator -o yaml >> olm-logs.txt' EXIT
          operator-sdk olm install
          kubectl create ns mondoo-operator
          operator-sdk run bundle '${{ inputs.bundle-img }}' --namespace mondoo-operator --timeout 5m0s
          echo ${{ secrets.MONDOO_CLIENT }} | base64 -d > creds.json
          kubectl create secret generic mondoo-client --namespace mondoo-operator --from-file=config=creds.json
          rm creds.json
          kubectl apply -f config/samples/k8s_v1alpha1_mondooauditconfig.yaml
      - name: Install mondoo and run e2e test with olm
        run: |
          curl -sSL http://mondoo.io/download.sh | bash
          mv mondoo /usr/local/bin/ 
          make test/deployment
      - name: Clean up
        run: |
          operator-sdk cleanup mondoo-operator --namespace mondoo-operator
          operator-sdk olm uninstall
      - name: Upload olm logs artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: olm-logs
          path: /home/runner/work/mondoo-operator/mondoo-operator/olm-logs.txt
